<script lang="ts">
	import { browser } from '$app/environment'
	import { toggleBestSolve } from '$lib/stores/bestSolve'
	import { checkBestAverage, displayTime, formatTime, getAvg, pad } from '$lib/utils/timer-utils'
	import { solves as allSolves } from '$lib/stores/solves'
	import type { Solve } from '@prisma/client'

	export let label: string
	export let value: string | undefined = undefined
	export let best = false
	export let mobile = false
	export let solves: Solve[] | undefined = undefined
	export let count: number | undefined = undefined

	let modal: HTMLDialogElement
	let today: string

	function openModal() {
		if (browser) {
			if (solves && solves.length === count) {
				const date = new Date(Math.max(...solves.map(i => new Date(i.createdAt).getTime())))
				today = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`
				modal.showModal()
			} else if (best) {
				toggleBestSolve()
			}
		}
	}

	async function copyClipboard() {
		if (solves && count) {
			const date = new Date()
			await navigator.clipboard.writeText(
				`${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(
					date.getDate()
				)}-нд NomadTimer гаргасан\n${count} эвлүүлэлтийн дундаж ${getAvg(
					solves,
					count
				)}\n\nЭвлүүлэлтийн жагсаалт:\n${solves
					.map((i, index) => `${index + 1}. ${formatTime(i)}   ${i.scramble}`)
					.join('\n')}`
			)
		}
	}
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div
	class={`flex cursor-pointer rounded-xl bg-primary py-4 px-3 text-white md:px-4 ${
		best ? 'w-full' : 'w-1/2'
	} ${mobile ? 'justify-evenly' : 'justify-between'}`}
	on:click={openModal}
>
	<span>{label}</span>
	<span class={`${count && checkBestAverage($allSolves, count)}`}>
		{#if solves}
			{#if solves.length !== count}
				{displayTime(0)}
			{:else}
				{getAvg(solves, count)}
			{/if}
		{:else}
			{value}
		{/if}
	</span>
</div>

{#if solves && solves.length === count}
	<dialog
		bind:this={modal}
		class="py-4 px-4 w-4/5 max-w-6xl font-sans bg-white rounded-xl md:px-0 lg:w-auto text-primary"
	>
		<div class="mx-auto w-full md:w-3/5">
			<h2 class="text-2xl text-center md:text-3xl">Avg status</h2>
			<p class="text-center">Generated By Nomad timer on {today}</p>
			<div class="mx-auto mt-6">
				<div
					class="flex items-center w-full text-lg text-center text-white rounded-xl bg-secondary"
				>
					<div class={`rounded-xl bg-primary p-4 md:w-1/5 ${label.length > 5 ? 'w-2/5' : 'w-1/5'}`}>
						{label}
					</div>
					<div class="w-4/5 text-center">
						{getAvg(solves, solves.length)}
					</div>
				</div>
			</div>
		</div>
		<h3 class="mt-8 text-3xl text-center">Эвлүүлэлтийн жагсаалт</h3>
		<div class="overflow-y-auto pr-4 mx-2 mt-2 w-5/6 max-h-72 text-2xl md:mx-auto md:w-3/4">
			{#each solves as solve, index}
				<div class="flex gap-4 py-2">
					<span>{index + 1}.</span>
					<span>{formatTime(solve)}</span>
					<span class="overflow-hidden whitespace-nowrap text-ellipsis">{solve.scramble}</span>
				</div>
			{/each}
		</div>
		<form method="dialog" class="flex gap-4 justify-center mt-2">
			<button class="py-2 px-4 text-xl text-white rounded-xl bg-primary" value="close">Close</button
			>
			<button class="py-2 px-4 text-xl text-white rounded-xl bg-primary" on:click={copyClipboard}
				>Copy</button
			>
		</form>
	</dialog>
{/if}
