<script lang="ts">
	import { browser } from '$app/environment'
	import { displayTime, formatTime, getAvg, pad } from '$lib/utils/timer-utils'
	import type { Solve } from '@prisma/client'

	export let label: string
	export let value: string | undefined = undefined
	export let best = false
	export let mobile = false
	export let solves: Solve[] | undefined = undefined
	export let count: number | undefined = undefined

	let modal: HTMLDialogElement

	function openModal() {
		if (browser && solves && solves.length === count) {
			modal.showModal()
		}
	}

	async function copyClipboard() {
		if (solves && count) {
			const date = new Date()
			await navigator.clipboard.writeText(
				`${date.getFullYear()}-${pad(date.getMonth())}-${pad(
					date.getDate()
				)}-д NomamTimer гаргасан\n${count} эвлүүлэлтийн дундаж ${getAvg(
					solves,
					count
				)}\n\nЭвлүүлэлтийн жагсаалт:\n${solves
					.map((i, index) => `${index + 1}. ${formatTime(i)}   ${i.scramble}`)
					.join('\n')}`
			)
		}
	}
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div
	class={`flex rounded-xl py-4 px-3 text-white md:px-4 ${
		best ? 'w-full' : 'w-1/2 cursor-pointer'
	} ${mobile ? 'justify-evenly bg-mobileAverage' : 'justify-between bg-sidebarElement'}`}
	on:click={openModal}
>
	<span>{label}</span>
	{#if solves}
		{#if solves.length !== count}
			<span>{displayTime(0)}</span>
		{:else}
			<span>{getAvg(solves, solves.length)}</span>
		{/if}
	{:else}
		<span>{value}</span>
	{/if}
</div>

{#if solves && solves.length === count}
	<dialog bind:this={modal} class="rounded-xl bg-[#454F57] py-4 px-4 font-sans text-white md:px-0">
		<div class="mx-auto w-full md:w-3/5">
			<h2 class="text-center text-2xl text-white md:text-3xl">Avg status</h2>
			<p class="text-center text-[#697279]">Generated By Nomad timer on 2023-02-11</p>
			<div class="mx-auto mt-6">
				<div class="flex w-full items-center rounded-xl bg-[#272A2D] text-center text-lg">
					<div
						class={`rounded-xl bg-[#33393E] p-4 md:w-1/5 ${label.length > 5 ? 'w-2/5' : 'w-1/5'}`}
					>
						{label}
					</div>
					<div class="w-4/5 text-center">
						{getAvg(solves, solves.length)}
					</div>
				</div>
			</div>
			<h3 class="mt-8 text-xl">Эвлүүлэлтийн жагсаалт</h3>
			<div class="scrollbar mt-2 max-h-72 overflow-y-auto pr-4 text-2xl">
				{#each solves as solve, index}
					<div class="flex gap-4 py-2">
						<span>{index + 1}.</span>
						<span>{formatTime(solve)}</span>
						<span class="overflow-hidden text-ellipsis whitespace-nowrap">{solve.scramble}</span>
					</div>
				{/each}
			</div>
			<form method="dialog" class="mt-2 flex justify-center gap-4">
				<button class="button py-2 px-4 text-xl" value="close">Close</button>
				<button class="button py-2 px-4 text-xl" on:click={copyClipboard}>Copy</button>
			</form>
		</div>
	</dialog>
{/if}
